spring:
  application:
    name: tms

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    show-sql: true