spring:
  application:
    name: tms

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nassimmakdi2001@gmail.com}
    password: ${MAIL_PASSWORD:tetw hbxv kawr mnbi}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true